### ISSUE TITLE
Damage system change

### ISSUE THREAD

**Issue by asyncmeonov** [Gorea235/Uni-UniversityDominationA3#14]
We did discuss that the change of the damage system is not needed as this one works, but as more as I get into the requirements specification, the more the word "balance" comes in (five times across four requirements to be precise). It is still not necessary to bother, but just to voice an idea, I think we can do better by simply changing their 
`int attackingUnitRoll = Random.Range(1, (5 + attackingUnit.Level)) + attackingUnit.Owner.Beer;`
` int defendingUnitRoll = Random.Range(1, (5 + defendingUnit.Level)) + defendingUnit.Owner.Knowledge;`
and nothing else.
For example, speaking in dice terms or dice, their mechanism equates to `1d[5+level] + bonus` which gives a lower bound (which in dice terms is satisfied 100% of the time) of `1+bonus` which is OP when someone gets six pints from the minigame. Wouldn't something like `1d[5 + level + bonus]` be better? In that way, your lower bound is still the same as everybody elses (which is 1) but by increasing the range you can roll with your bonuses [you are increasing the mean value of you roll](http://anydice.com/program/eca6), which is I think better than the flat-bonus-obliteration.

**Comment by luvies** [comment]
I do think an adjustment is needed, as in a standard playthrough, if you win the minigame at least once it will almost immediately put all of your units in an untouchable position.

(before I continue, I need to point out that `Random.Range` is exclusive in the upper bound, meaning that the current maximum roll is 1 less than the calculated number, e.g. a level of 1 results in an upper exclusive bound of 6, meaning that it can roll from 1-5)

Lets say someone wins the minigame with *most* of their health left; this means that they would get 5 knowledge and 5 beer straight up, permanently for the rest of the game. Currently, it means that even if your unit is level one, someone with 0 beer & knowledge would never be able to beat it, even with a level 5. This isn't a major issue to start with, since everyone starts with a certain amount of beer & knowledge due to the starting landmarks, but if someone loses their landmarks, it means that they have no way of ever getting back into the game without finding the PVC, which I think would be a problem.

However, the solution you put forward comes with a major downside, which is that a player with 0 knowledge & beer, and a level 1 unit, could beat someone else with a level 5 unit and a lot of knowledge/beer. This feels completely unfair to the other player, since they are at a completely clear advantage in that situation but still lose because 'RNG'.

A solution might be to make units of a lower level automatically lose to higher level units, with beer increasing the level difference the attacker can still be successful at, and knowledge decreasing it (A flat cutoff might not work properly, but a curve that fulfils this might). This way, a unit at level 1 and 0 beer would never be able to kill a unit at level 5 with 15 knowledge, but a unit at level 1 and 15 beer could much more easily take on a unit at level 5 with 0 knowledge.

I would need to think and test to see what ranges, adjustments, and functions would be needed to make this work nicely, but I think this system brings about the most fairness overall.

**Comment by luvies** [comment]
Due to time constraints and complexity, we have decided against these changes.
