### ISSUE TITLE
Minigame

### ISSUE THREAD

**Issue by asyncmeonov** [Gorea235/Uni-UniversityDominationA3#2]
A subteam that will be formed soon will have the task to create a minigame.No-one's requirements do not specify any minigame restrictions (appart from the risk at F3 so we will have to devise them. Here I will list some of the needs for the minigame and do feel free to expand.

1. Minigame shouldn't take _too long_ (we need to specify _"too long"_)
2. Minigame should quantify some main-game bonus that upon exiting will be transferred to the player that has initiated the minigame ( note that we have the "pints" and "books" system at our disposal)
3. Minigame should be serializable (this is more of a question than a need at this point, because the requirements don't specifically require from us to be able to always save the game)

**Comment by luvies** [comment]
Currently, we have the plan to make 2 mini-games simultaneously, a complex one and a simple one. This is how it will work:

### Simple

The simple game will just be a Space Invader clone, using geese & ducks as the ships that slide down. We will also use Central Hall as the space ship that flies above as a bonus target.

### Complex

The complex game will be a Doom clone. Like a full on (3D possibly) Doom clone. The enemies will be ducks and geese, with possibly a final boss (depending on length). We might also use multiple levels and randomly select (each can be based on a building on HES East). Killing will only cause enemies to 'poof', rather than properly die, in order to meet with the requirements.

Since the second game is significantly more complex, we have decided to develop both in parallel, so that if we are unable to complete the second, we can just use the first.

**Comment by luvies** [comment]
Currently I'm planning on giving the user the option to switch between the 'Simple' and 'Complex' minigames in the options menu. This is because the simple minigame is basically done, and the complex one is mostly done, and since so much work has been put into both (and it isn't too much to add a menu option extra), we might as well include both in the final product.

**Comment by luvies** [comment]
We're only going to use the complex minigame, however both minigames will work with a simple change on which scene is loaded.

**Comment by luvies** [comment]
Minigames are completed, the only thing left is for the main game to load them when needed, which is to be handled in #3
