### ISSUE TITLE
Menu System

### ISSUE THREAD

**Issue by luvies** [Gorea235/Uni-UniversityDominationA3#7]
The game needs a menu system in order to drive the game and player setup. This menu system should also include things like options and saving/loading.

Todo:

- [x] Main menu
- [ ] Options menu (optional)
  - [ ] Functioning options
- [x] Load menu
- [ ] Pause menu (should be done via overlay over current game)
  - [ ] In-game options menu
  - [x] Saving menu

**Comment by luvies** [comment]
The requirements don't directly state anything about options, at least to do with music and sounds, and so I have set that point as optional.

**Comment by asyncmeonov** [comment]
Note: [GUI report](https://sepr-team-margaret.github.io/content/GUI2.pdf) has explicitly chosen a set of four colours that are justified for requirement N8 so I suggest to remove the option of allowing players to choose a colour at the start of the game. Have in mind: current game has no concept of colleges, so that is completely fine.

**Comment by luvies** [comment]
We're not implementing the options menu due to it not being required for assessment 3
